# This workflow will build a Java project with Gradle and deploy to azure web app
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: 
      -development
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      
    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew bootJar
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fertigbackend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0a3b804a671a46baa4dbc23eed272451 }}
        package: '${{ github.workspace }}/build/libs/*.jar'
    
